#!/usr/bin/env python3
"""
Build Complete NSE Symbol List for TradEdge Scanner
=====================================================
Generates nse_symbols.json with 1400+ NSE stocks across ALL market caps.

Sources (priority order):
  1. NSE EQUITY_L.csv (all ~2400 listed equities) — requires network
  2. Built-in list: 2803 curated symbols (mega → micro cap)

Usage:
  python scripts/build_symbol_list.py                  # Auto-fetch from NSE + merge built-in
  python scripts/build_symbol_list.py --builtin-only   # Use built-in 1400+ list (no network)
  python scripts/build_symbol_list.py --from-csv X.csv # From Dhan/Screener/ChartInk CSV
"""

import argparse
import csv
import io
import json
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = SCRIPT_DIR / "nse_symbols.json"


def fetch_nse_equity_list() -> list[dict]:
    """Fetch ALL NSE listed equities from official EQUITY_L.csv (~2400 symbols)."""
    import requests
    url = "https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Accept": "text/csv,*/*",
        "Referer": "https://www.nseindia.com/",
    }
    print(f"  Fetching {url} ...")
    try:
        session = requests.Session()
        session.get("https://www.nseindia.com/", headers=headers, timeout=10)
        time.sleep(1)
        resp = session.get(url, headers=headers, timeout=30)
        resp.raise_for_status()
        session.close()
        reader = csv.DictReader(io.StringIO(resp.text))
        symbols = []
        for row in reader:
            symbol = row.get("SYMBOL", "").strip()
            name = row.get("NAME OF COMPANY", "").strip()
            if not symbol:
                continue
            symbols.append({"symbol": symbol, "name": name or symbol, "sector": "Unknown"})
        print(f"  ✅ Got {len(symbols)} symbols from NSE EQUITY_L.csv")
        return symbols
    except Exception as e:
        print(f"  ⚠ Failed to fetch from NSE: {e}")
        return []


def build_from_csv(csv_path: str) -> list[dict]:
    """Parse Dhan / Screener / ChartInk CSV export."""
    symbols = []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            symbol = (row.get("Symbol") or row.get("SYMBOL") or "").strip().strip('"')
            # Clean ChartInk suffixes
            for suffix in ["-EQ", "-SM-SM", "-ST-ST", "-SM", "-BE", "-BZ"]:
                symbol = symbol.replace(suffix, "")
            name = (row.get("Company") or row.get("Name") or row.get("Company Name") or symbol).strip().strip('"')
            sector = (row.get("Industry") or row.get("Sector") or "Unknown").strip()
            if symbol:
                symbols.append({"symbol": symbol, "name": name, "sector": sector})
    return symbols


def get_builtin_symbols() -> list[dict]:
    """
    Built-in list of 2803 NSE symbols across ALL market caps.
    Mega cap → Large cap → Mid cap → Small cap → Micro cap.
    Source: Nifty 50 + Next 50 + Midcap 150 + ChartInk Smallcap scan (MCap ₹300-5000 Cr).
    """
    symbols = [
        "RELIANCE","HDFCBANK","BHARTIARTL","SBIN","ICICIBANK","TCS","BAJFINANCE","HINDUNILVR",
        "INFY","LICI","LT","SUNPHARMA","MARUTI","ITC","M&M","AXISBANK",
        "NTPC","KOTAKBANK","TITAN","TATAMOTORS","TVSMOTOR","GRASIM","INDIGO","DIVISLAB",
        "WIPRO","HCLTECH","ADANIENT","ADANIPORTS","POWERGRID","ASIANPAINT","BAJAJFINSV","NESTLEIND",
        "ULTRACEMCO","JSWSTEEL","TATASTEEL","ONGC","COALINDIA","TECHM","DRREDDY","CIPLA",
        "HEROMOTOCO","EICHERMOT","APOLLOHOSP","BPCL","HINDALCO","SHRIRAMFIN","BRITANNIA","SBILIFE",
        "HDFCLIFE","TRENT","BANKBARODA","CANBK","PNB","IDFCFIRSTB","FEDERALBNK","INDIANB",
        "BANDHANBNK","AUBANK","RBLBANK","DMART","TATACONSUM","DABUR","GODREJCP","COLPAL",
        "MARICO","PIDILITIND","BERGEPAINT","HAVELLS","VOLTAS","WHIRLPOOL","CROMPTON","DIXON",
        "POLYCAB","KEI","SIEMENS","ABB","CUMMINSIND","THERMAX","BEL","HAL",
        "BHEL","IRCTC","IRFC","RVNL","ZOMATO","PAYTM","NYKAA","POLICYBZR",
        "PERSISTENT","LTIM","MPHASIS","COFORGE","LUPIN","AUROPHARMA","BIOCON","ALKEM",
        "TORNTPHARM","SYNGENE","IPCALAB","LAURUSLABS","NATCOPHARMA","DLF","GODREJPROP","OBEROIRLTY",
        "PRESTIGE","BRIGADE","PHOENIXLTD","LODHA","PIIND","ATUL","DEEPAKNITRI","CLEAN",
        "FLUOROCHEM","SRF","NAVINFLUOR","AARTI","TATAPOWER","ADANIGREEN","ADANIENSOL","NHPC",
        "SJVN","RECLTD","PFC","HUDCO","JINDALSTEL","SAIL","NMDC","VEDL",
        "NATIONALUM","HINDZINC","RATNAMANI","MUTHOOTFIN","MANAPPURAM","CHOLAFIN","LICHSGFIN","BAJAJ-AUTO",
        "ASHOKLEY","ESCORTS","TIINDIA","MRF","BALKRISIND","APOLLOTYRE","CEAT","CONCOR",
        "GAIL","IOC","HPCL","PETRONET","MOTHERSON","BOSCHLTD","MINDAIND","EXIDEIND",
        "AMBUJACEM","ACC","DALMIACEM","RAMCOCEM","JKCEMENT","STARHEALTH","MAXHEALTH","FORTIS",
        "MEDANTA","NAUKRI","LTTS","TATAELXSI","HAPPSTMNDS","SONACOMS","ZENSAR","BSOFT",
        "MASTEK","CANFINHOME","ICICIGI","ICICIPRULI","SBICARD","PAGEIND","RAYMOND","ARVIND",
        "TTML","HINDCOPPER","MCX","INDIAMART","ANGELONE","LALPATHLAB","METROPOLIS","KIMS",
        "RAINBOW","CGCL","JIOFINANCE","AFFLE","ROUTE","LATENTVIEW","KAYNES","INTELLECT",
        "BIRLASOFT","KPITTECH","CYIENT","NEWGEN","DATAPATTNS","SUZLON","INOXWIND","IIFL",
        "MOTILALOFS","ABSLAMC","CDSL","BSE","CAMS","KFINTECH","JUBLFOOD","DEVYANI",
        "WESTLIFE","INDHOTEL","LEMONTRE","CHALET","ABCAPITAL","POONAWALLA","CREDITACC","AAVAS",
        "HOMEFIRST","APTUS","REPCO","SUNDARMFIN","MAZDOCK","COCHINSHIP","GRSE","GARDENREACH",
        "JSWENERGY","CESC","TORNTPOWER","KECINTL","KALPATPOWR","POWERMECH","GPPL","GIPCL",
        "PGHH","EMAMILTD","JYOTHYLAB","VGUARD","CENTURYPLY","GREENPLY","ASTRAL","SUPREMEIND",
        "PRINCEPIPE","FINOLEX","APLAPOLLO","GNFC","GSFC","CHAMBLFERT","COROMANDEL","UPL",
        "RALLIS","SUMICHEM","ABFRL","SHOPERSTOP","MANYAVAR","CAMPUS","KALYANKJIL","SENCO",
        "PCJEWELLER","PVRINOX","SUNTV","NAZARA","NETWORK18","TV18BRDCST","ZEEL","GRINFRA",
        "PNCINFRA","IRB","KNR","NCC","NBCC","JKTYRE","ENDURANCE","SWARAJ",
        "SKFINDIA","SCHAEFFLER","TIMKEN","CARBORUNIV","GRINDWELL","NIPPOBATRS","BLUEDART","ALLCARGO",
        "VARUNBEV","UNITDSPR","RADICO","AJANTPHARM","GRANULES","GLAND","GLENMARK","ZYDUSLIFE",
        "ERIS","MANKIND","HONAUT","GILLETTE","3MINDIA","FINEORG","TATACHEM","NOCIL",
        "VINATI","EIDPARRY","RENUKA","DWARIKESH","TRIVENI","TANLA","RATEGAIN","CMSINFO",
        "SOLARINDS","TTKPRESTIG","HAWKINCOOK","IREDA","TATATECH","CELLO","DOMS","IXIGO",
        "FIRSTCRY","BAJAJHOUS","SAGILITY","NTPCGREEN","WAAREE","ACME","AFCONS","SWIGGY",
        "NIVA","MOBIKWIK","ZAGGLE","NETWEB","MAPMYINDIA","SBFC","YESBANK","IDBI",
        "OIL","SAREGAMA","TIPS","BALRAMCHIN","DEEPAKFERT","RCF","FACT","NFL",
        "HDFCAMC","TRIDENT","WELSPUNLIV","KPRMILL","GOCOLORS","20MICRONS","5PAISA","63MOONS",
        "AARTIDRUGS","AARTISURF","ABCOTS","ABINFRA","ABSMARINE","ACCELYA","ACCENTMIC","ACL",
        "ADFFOODS","ADOR","ADSL","ADVAIT","ADVANCE","ADVANIHOTR","ADVENTHTL","ADVENZYMES",
        "AEPL","AEROENTER","AEROFLEX","AFIL","AFSL","AGARIND","AGI","AGIIL",
        "AHCL","AIMTRON","AJMERA","ALBERTDAVD","ALEMBICLTD","ALGOQUANT","ALICON","ALLDIGI",
        "ALLTIME","ALPEXSOLAR","AMANTA","AMBIKCO","AMCL","AMNPLST","AMRUTANJAN","ANDHRAPAP",
        "ANDHRSUGAR","ANNAPURNA","ANONDITA","ANTELOPUS","ANUHPHR","ANUP","APCL","APCOTEXIND",
        "APEX","APOLLOPIPE","APRAMEYA","APS","APTECHT","AQYLON","ARFIN","ARIES",
        "ARIHANTACA","ARIHANTCAP","ARIHANTSUP","ARIS","ARKADE","ARMANFIN","ARROWGREEN","ARSSBL",
        "ARTEMISMED","ARVSMART","ASAL","ASALCBR","ASHAPURMIN","ASHIANA","ASHOKA","ASIANENE",
        "ASIANHOTNR","ASIANTILES","ASTEC","ATL","ATMASTCO","ATULAUTO","AURIONPRO","AURUM",
        "AUTOAXLES","AVADHSUGAR","AVANTEL","AVONMORE","AVTNPL","AWFIS","AWHCL","AXITA",
        "AYE","AYMSYNTEX","BAHETI","BAJAJCON","BAJAJELEC","BAJAJHCARE","BAJAJHIND","BAJAJINDEF",
        "BAJEL","BALAJITELE","BALAMINES","BALMLAWRIE","BANARISUG","BANSALWIRE","BANSWRAS","BASILIC",
        "BBL","BBTCL","BCG","BCLIND","BEDMUTHA","BELLACASA","BEPL","BESTAGRO",
        "BETA","BFINVEST","BFUTILITIE","BGRENERGY","BHAGCHEM","BHAGERIA","BHAGYANGR","BHARATRAS",
        "BHARATSE","BHARATWIRE","BIGBLOC","BIL","BIRLACABLE","BIRLAMONEY","BIRLANU","BLAL",
        "BLISSGVS","BLKASHYAP","BLSE","BLUSPRING","BMWVENTLTD","BODALCHEM","BOMDYEING","BORANA",
        "BOROLTD","BOROSCI","BOSCH-HCIL","BRIGHOTEL","BSHSL","BUILDPRO","BUTTERFLY","C2C",
        "CAMLINFINE","CANTABIL","CAPACITE","CAPILLARY","CAPITALSFB","CARERATING","CARRARO","CARYSIL",
        "CCAVENUE","CCCL","CEIGALL","CEINSYS","CELLECOR","CENTENKA","CENTRUM","CENTUM",
        "CEWATER","CGRAPHICS","CHANDAN","CHAVDA","CHEMBONDCH","CHEMCON","CHEMFAB","CHEMPLASTS",
        "CHEVIOT","CIFL","CIGNITITEC","CLSEL","CNL","COASTCORP","COFFEEDAY","COMSYN",
        "CONFIPET","CONNPLEX","CONSOFINVT","CONTROLPR","COSMOFIRST","CPEDU","CRAMC","CREST",
        "CRIZAC","CSLFINANCE","CYBERTECH","CYIENTDLM","DALMIASUG","DAMCAPITAL","DANISH","DATAMATICS",
        "DAVANGERE","DBCORP","DBEIL","DBOL","DCAL","DCI","DCMSIL","DCMSRIND",
        "DCW","DCXINDIA","DDEVPLSTIK","DECCANCE","DEEDEV","DEEPINDS","DELTACORP","DEN",
        "DENORA","DENTA","DENTALKART","DEVX","DHAMPURSUG","DHANBANK","DHANUKA","DHARIWAL",
        "DHARMAJ","DHUNINV","DIAMONDYD","DICIND","DIFFNKG","DIGISPICE","DIGITIDE","DISHTV",
        "DIVGIITTS","DIVINEHIRA","DLINKINDIA","DMCC","DOLATALGO","DOLLAR","DOLPHIN","DONEAR",
        "DPABHUSHAN","DPEL","DPSCLTD","DREAMFOLKS","DREDGECORP","DSSL","DVL","DWARKESH",
        "DYCL","E2E","E2ERAIL","EASEMYTRIP","EBGNG","ECOSMOBLTY","EFCIL","EFFWA",
        "EIEL","EIFFL","EIHAHOTELS","EIMCOELECO","EKC","ELDEHSG","ELECTCAST","ELECTHERM",
        "ELIN","ELLEN","EMAMIPAP","EMIL","EMKAY","EMSLIMITED","EMUDHRA","ENCOMPAS",
        "ENIL","ENTERO","EPACK","EPACKPEB","EPIGRAL","ESAFSFB","ESFL","ESSARSHPNG",
        "ESTER","ETL","EUROBOND","EUROPRATIK","EVEREADY","EVERESTIND","EXCELINDUS","EXCELSOFT",
        "EXICOM","EXIMROUTES","EXPLEOSOL","EXXARO","FABTECH","FAIRCHEMOR","FAZE3Q","FCL",
        "FEDFINA","FELIX","FILATEX","FINKURVE","FINOPB","FISCHER","FLAIR","FLYSBS",
        "FMGOETZE","FOCE","FOCUS","FOODSIN","FOSECOIND","FRESHARA","FUSION","GALAPREC",
        "GANDHAR","GANDHITUBE","GANECOS","GANESHBE","GANESHCP","GANESHIN","GARUDA","GATEWAY",
        "GAUDIUMIVF","GCSL","GEECEE","GEMAROMA","GENESYS","GENUSPAPER","GEOJITFSL","GFLLIMITED",
        "GGBL","GHCL","GHCLTEXTIL","GICHSGFIN","GICL","GINNIFILA","GIRIRAJ","GJL",
        "GKENERGY","GKSL","GKWLIMITED","GLOBAL","GLOBUSSPR","GLOSTERLTD","GLOTTIS","GMBREW",
        "GMMPFAUDLR","GNA","GOCLCORP","GODAVARIB","GOKEX","GOKUL","GOKULAGRO","GOLDIAM",
        "GOLDKART","GOODLUCK","GOPAL","GPECO","GPTHEALTH","GPTINFRA","GREAVESCOT","GREENPANEL",
        "GREENPOWER","GRETEX","GRMOVER","GRPLTD","GTLINFRA","GTPL","GUFICBIO","GUJALKALI",
        "GUJAPOLLO","GUJTHEM","GULFOILLUB","GULPOLY","GVKPIL","GVPIL","HALDER","HALEOSLABS",
        "HARDWYN","HARIOMPIPE","HARRMALAYA","HARSHA","HATHWAY","HCC","HCL-INSYS","HEIDELBERG",
        "HEMIPROP","HERANBA","HERCULES","HERITGFOOD","HESTERBIO","HEXATRADEX","HGINFRA","HGS",
        "HIGREEN","HIKAL","HILINFRA","HIMATSEIDE","HINDCOMPOS","HINDOILEXP","HINDWAREAP","HIRECT",
        "HITECH","HITECHGEAR","HLEGLAS","HLVLTD","HMAAGRO","HMT","HMVL","HONDAPOWER",
        "HPL","HPTL","HTMEDIA","HUBTOWN","HUHTAMAKI","IBULLSLTD","ICEMAKE","ICIL",
        "IDEAFORGE","IFBAGRO","IFBIND","IFGLEXPOR","IGARASHI","IGCL","IGPL","IKIO",
        "IMAGICAA","IMPAL","INA","INDIANHUME","INDIGOPNTS","INDIQUBE","INDNIPPON","INDOAMIN",
        "INDOBORAX","INDOCO","INDOFARM","INDORAMA","INDOSTAR","INDOTECH","INDOTHAI","INDRAMEDCO",
        "INDSWFTLAB","INFINIUM","INFLUX","INFOBEAN","INNOVACAP","INNOVANA","INSECTICID","INSPIRISYS",
        "INTERARCH","INTLCONV","IOLCP","IONEXCHANG","IPL","IRIS","IRISDOREME","IRMENERGY",
        "ITDC","IVALUE","IZMO","JAGRAN","JAGSNPHARM","JAICORPLTD","JAMNAAUTO","JARO",
        "JASH","JAYAGROGN","JAYBARMARU","JAYKAY","JGCHEM","JINDALPHOT","JINDALPOLY","JINDRILL",
        "JINDWORLD","JISLJALEQS","JITFINFRA","JKIL","JNKINDIA","JPASSOCIAT","JPOLYINVST","JSFB",
        "JTEKTINDIA","JTLIND","JUBLCPL","JUNIPER","JUSTDIAL","JYOTISTRUC","KABRAEXTRU","KALAMANDIR",
        "KAMATHOTEL","KAMDHENU","KANPRPLA","KAPSTON","KARNIKA","KAVDEFENCE","KAYA","KCP",
        "KDDL","KECL","KELLTONTEC","KERNEX","KHAICHEM","KICL","KILITCH","KIRIINDUS",
        "KIRLOSIND","KITEX","KKCL","KMEW","KNAGRI","KNRCON","KODYTECH","KOKUYOCMLN",
        "KOLTEPATIL","KOPRAN","KOTHARIPET","KOTHARIPRO","KOTYARK","KPEL","KRISHANA","KRISHIVAL",
        "KRISHNADEF","KRITI","KRITINUT","KRMAYURVED","KRONOX","KROSS","KRSNAA","KRYSTAL",
        "KSCL","KSHINTL","KSL","KSOLVES","KUANTUM","LANDMARK","LAOPALA","LAXMIDENTL",
        "LAXMIINDIA","LEMERITE","LGHL","LIBERTSHOE","LIKHITHA","LINC","LINCOLN","LOKESHMACH",
        "LORDSCHLO","LUMAXIND","LUXIND","LXCHEM","MAANALU","MACPOWER","MADRASFERT","MAGADSUGAR",
        "MAHASTEEL","MAHEPC","MAHLOG","MAITHANALL","MALLCOM","MAMATA","MANAKCOAT","MANAKSIA",
        "MANAKSTEEL","MANALIPETC","MANBA","MANCREDIT","MANGLMCEM","MANINDS","MANINFRA","MANOMAY",
        "MANORG","MARATHON","MARINE","MARKOLINES","MARSONS","MASON","MASTERTR","MATRIMONY",
        "MAWANASUG","MAXIND","MAYURUNIQ","MAZDA","MBAPL","MBEL","MBLINFRA","MCLEODRUSS",
        "MCLOUD","MEDIASSIST","MEDICAMEQ","MEDICO","MEGATHERM","MEIL","MENONBE","MGEL",
        "MICEL","MIDWESTLTD","MINDTECK","MIRCELECTR","MIRZAINT","MMFL","MMP","MODINATUR",
        "MODIS","MODISONLTD","MOL","MOLDTECH","MOLDTKPAC","MONARCH","MONEYBOXX","MONOLITH",
        "MONTECARLO","MOREPENLAB","MOS","MOSCHIP","MOTISONS","MPSLTD","MSPL","MSTCLTD",
        "MTNL","MUFIN","MUFTI","MUKANDLTD","MUKKA","MUNJALAU","MUNJALSHOW","MUTHOOTCAP",
        "MUTHOOTMF","MVGJL","MVKAGRO","MWL","NACLIND","NAHARCAP","NAHARINDUS","NAHARPOLY",
        "NAHARSPING","NAMOEWASTE","NAVKARCORP","NAVNETEDUL","NBIFIN","NCLIND","NDL","NDLVENTURE",
        "NDRAUTO","NDTV","NELCAST","NELCO","NEOGEN","NEPTUNE","NEUEON","NGLFINE",
        "NIBE","NIITLTD","NIITMTS","NILASPACES","NILKAMAL","NINSYS","NITCO","NITINSPIN",
        "NORTHARC","NPST","NRAIL","NRBBEARING","NRL","NSIL","NUCLEUS","OAL",
        "OBSCP","OCCLLTD","OMAXE","OMINFRAL","OMNI","ONEPOINT","ONMOBILE","ONWARDTEC",
        "OPTIEMUS","ORBTEXP","ORCHPHARMA","ORIANA","ORICONENT","ORIENTBELL","ORIENTCEM","ORIENTCER",
        "ORIENTELEC","ORIENTHOT","ORIENTPPR","ORIENTTECH","ORISSAMINE","OSELDEVICE","OSWALAGRO","OSWALGREEN",
        "OSWALPUMPS","PACEDIGITK","PAISALO","PAKKA","PANACEABIO","PANACHE","PANAMAPET","PANSARI",
        "PARACABLES","PARAGMILK","PARIN","PARKHOTELS","PARTH","PASHUPATI","PASUPTAC","PATELENG",
        "PATELRMART","PATILAUTOM","PAUSHAKLTD","PCCL","PDMJEPAPER","PDSL","PELATRO","PENIND",
        "PENINLAND","PFS","PILANIINVS","PITTIENG","PIXTRANS","PLASTIBLEN","PLATIND","PNBGILTS",
        "PNGSREVA","POCL","POKARNA","POLYPLEX","POLYSIL","PPL","PRABHA","PRAKASH",
        "PRAMARA","PRECAM","PRECOT","PREMEXPLN","PREMIERPOL","PRIMESECU","PRIMO","PRIZOR",
        "PROSTARM","PROTEAN","PROV","PROZONER","PSPPROJECT","PTC","PTL","PUNJABCHEM",
        "PURVA","PVP","PVSL","PYRAMID","QUADFUTURE","QUESS","QUICKHEAL","RACLGEAR",
        "RADHIKAJWE","RADIANTCMS","RAIN","RAJESHEXPO","RAJOOENG","RAJRATAN","RAJRILTD","RAMANEWS",
        "RAMAPHO","RAMASTEEL","RAMCOIND","RAMCOSYS","RAMKY","RAMRAT","RANEHOLDIN","RATNAVEER",
        "RAYMONDLSL","RAYMONDREL","RBA","RBMINFRA","RBZJEWEL","REFEX","REGAAL","RELINFRA",
        "RELTD","REMSONSIND","REMUS","REPCOHOME","REPRO","RESPONIND","RGL","RHETAN",
        "RHL","RICOAUTO","RIIL","RISHABH","RITCO","RKSWAMY","RMDRIP","RML",
        "RNBDENIMS","RNFI","ROHLTD","ROLEXRINGS","ROSSARI","ROSSTECH","ROTO","RPEL",
        "RPGLIFE","RPPINFRA","RPSGVENT","RPTECH","RSWM","RSYSTEMS","RTNINDIA","RTNPOWER",
        "RUBFILA","RUBYMILLS","RUCHIRA","RUPA","RUSHIL","RUSTOMJEE","S&SPOWER","SAAKSHI",
        "SAATVIKGL","SACHEEROME","SADHNANIQ","SAFEENTP","SAGCEM","SAHANA","SAHASRA","SAKAR",
        "SAKSOFT","SALASAR","SALSTEEL","SALZERELEC","SAMBHV","SAMHI","SANATHAN","SANDESH",
        "SANDHAR","SANGAMIND","SANGHIIND","SANGHVIMOV","SANSTAR","SARLAPOLY","SARTELE","SARVESHWAR",
        "SASKEN","SASTASUNDR","SATIA","SATIN","SAURASHCEM","SAWALIYA","SBC","SBCL",
        "SBGLP","SCHAND","SCILAL","SCODATUBES","SCPL","SDBL","SEAMECLTD","SEJALLTD",
        "SENORES","SEPC","SERVOTECH","SESHAPAPER","SETL","SGFIN","SGIL","SHAH",
        "SHALBY","SHALPAINTS","SHANTIGEAR","SHANTIGOLD","SHARDAMOTR","SHAREINDIA","SHILCTECH","SHIVALIK",
        "SHIVAUM","SHK","SHREDIGCEM","SHREEPUSHK","SHREERAMA","SHRIAHIMSA","SHRINGARMS","SHRIRAMPPS",
        "SICALLOG","SIGACHI","SIGMA","SIGMAADV","SIGNPOST","SILINV","SILVERTUC","SIMPLEXINF",
        "SINCLAIR","SINDHUTRAD","SIRCA","SIS","SIYSIL","SJLOGISTIC","SJS","SKIPPER",
        "SKMEGGPROD","SMARTWORKS","SMCGLOBAL","SMSPHARMA","SNOWMAN","SOFTTECH","SOLARA","SOLARWORLD",
        "SOLEX","SOMANYCERA","SOMATEX","SOTL","SOUTHWEST","SPAL","SPANDANA","SPARC",
        "SPECIALITY","SPECTRUM","SPIC","SPMLINFRA","SPORTKING","SRD","SREEL","SRGHFL",
        "SRHHYPOLTD","SRM","SSEGL","SSWL","STALLION","STANLEY","STCINDIA","STEELCAS",
        "STEELXIND","STEL","STERTOOLS","STLNETWORK","STOVEKRAFT","STUDDS","STYL","STYLAMIND",
        "STYLEBAAZA","STYRENIX","SUBEXLTD","SUBROS","SUDARCOLOR","SUKHJITS","SULA","SUMEETINDS",
        "SUMMITSEC","SUNCLAY","SUNDROP","SUNFLAG","SUNLITE","SUNTECK","SUPREMEINF","SUPREMEPWR",
        "SUPRIYA","SURAJEST","SURAJLTD","SURAKSHA","SURYAROSNI","SURYODAY","SUTLEJTEX","SUVEN",
        "SUYOG","SVLL","SWARAJENG","SWELECTES","SWSOLAR","SYNCOMF","SYSTANGO","SYSTMTXC",
        "TAC","TAJGVK","TAKE","TALBROAUTO","TARACHAND","TARC","TARSONS","TASTYBITE",
        "TATVA","TBZ","TCC","TCIEXP","TCPLPACK","TEAMLEASE","TECHD","TECHLABS",
        "TEJASCARGO","TEMBO","TERASOFT","TEXINFRA","TEXRAIL","TFCILTD","THEINVEST","THEJO",
        "THEMISMED","THOMASCOOK","THOMASCOTT","TICL","TIIL","TIL","TINNARUBR","TIRUMALCHM",
        "TIRUPATI","TIRUPATIFL","TNPETRO","TNPL","TOLINS","TPLPLASTEH","TRACXN","TRANSTEEL",
        "TREJHARA","TREL","TRUALT","TTKHLTCARE","TVSELECT","TVSSCS","TVSSRICHAK","TVTODAY",
        "UDS","UEL","UFBL","UFLEX","UGARSUGAR","UGROCAP","UNICHEMLAB","UNIDT",
        "UNIECOM","UNIENTER","UNIHEALTH","UNIMECH","UNIPARTS","UNITECH","UNITEDPOLY","UNIVCABLES",
        "UNIVPHOTO","URJA","UTKARSHBNK","UTSSAV","UTTAMSUGAR","VADILALIND","VAIBHAVGBL","VAKRANGEE",
        "VALIANTORG","VARDMNPOLY","VASCONEQ","VEEDOL","VENKEYS","VENUSPIPES","VENUSREM","VERANDA",
        "VERTOZ","VGL","VHL","VHLTD","VIDHIING","VIDYAWIRES","VIESL","VIKRAN",
        "VILAS","VIMTALABS","VINCOFE","VINDHYATEL","VINSYS","VINYAS","VINYLINDIA","VIPIND",
        "VISAKAIND","VISASTEEL","VISHNU","VISHNUINFR","VIVIANA","VLSFINANCE","VMARCIND","VMART",
        "VPRPL","VRAJ","VRLLOG","VSSL","VSTIND","VSTTILLERS","WAAREEINDO","WALCHANNAG",
        "WANBURY","WCIL","WEALTH","WEBELSOLAR","WEL","WELINV","WENDT","WHEELS",
        "WINDLAS","WINDMACHIN","WONDERLA","WSI","WSTCSTPAPR","XCHANGING","XPROINDIA","XTGLOBAL",
        "YASHO","YATRA","YUKEN","ZEEMEDIA","ZIMLAB","ZODIAC","ZOTA","ZTECH",
        "ZUARI","ZUARIIND","MRPL","ITI","AKI","DCMFINSERV","SEMAC","CHENNPETRO",
        "CSBBANK","NGIL","SHRADHA","MKPL","GREENLAM","OLAELEC","ZYDUSWELL","TEJASNET",
        "ISHANCH","DEVIT","ADANIPOWER","MEGASTAR","EMMVEE","CURAA","BAFNAPH","AVROIND",
        "IL&FSENGG","EQUIPPP","GAYAPROJ","SANGINITA","GFSTEELS","CUB","SUNDARAM","BANARBEADS",
        "VIJIFIN","ARVEE","SRTL","HITECHCORP","ORTEL","JSWHL","SUPREME","SANWARIA",
        "SECMARK","ABSL10BANK","SMLMAH","QUINTEGRA","AADHARHFC","SUPREMEENG","DODLA","KRITIKA",
        "AURIGROW","ACUTAAS","HAPPYFORGE","ZENTEC","CANHLIFE","SANSERA","SPCENET","LMW",
        "LOTUSEYE","UNITEDTEA","NIRAJISPAT","AVG","VINATIORGA","TIPSMUSIC","BIKAJI","LINDEINDIA",
        "CUPID","XELPMOC","DCMSHRIRAM","VMM","ASHIMASYN","AJAXENGG","GLOBALE","SUMIT",
        "UNIVAFOODS","SHRIPISTON","AHLEAST","ETERNAL","SECURKLOUD","GVPTECH","GOLDTECH","TENNIND",
        "URBANCO","TMCV","JINDALSAW","DYNAMATECH","PFIZER","AKSHAR","ESABINDIA","LIBAS",
        "WEWIN","GODREJIND","MAHESHWARI","SETUINFRA","PIRAMALFIN","AETHER","SAILIFE","ASAHISONG",
        "KINGFA","QPOWER","J&KBANK","FORCEMOT","WAAREEENER","MAHAPEXLTD","CIEINDIA","PINELABS",
        "GENCON","BANCOINDIA","NIFTY50TR2XLEV","NIFTY50PR2XLEV","AVANTIFEED","CCL","JAIPURKURT","RRKABEL",
        "SEYAIND","OLECTRA","BALKRISHNA","KSR","VIPULLTD","INDIASHLTR","LEMONTREE","STARTECK",
        "CINEVISTA","TDPOWERSYS","MAHSEAMLES","SANOFICONR","MANORAMA","ANIKINDS","CREATIVEYE","CRAFTSMAN",
        "PREMIERENE","ARCHIES","VESUVIUS","BONLON","JLHL","MOALPHA50","MOM50","PRICOLLTD",
        "NIFTYAUTO","PICCADIL","LYKALABS","TRU","BANK10ADD","GODIGIT","VINEETLAB","SHREECEM",
        "NIFTYFINSERVICE","TBOTEK","AUTOBEES","MTARTECH","AUTOIETF","MHLXMIRU","VBL","BFSI",
        "APARINDS","ASKAUTOLTD","GROWW","HDFCSENSEX","EMCURE","THYROCARE","INDGN","FIVESTAR",
        "GMRAIRPORT","SENSEXETF","GLFL","SKFINDUS","EBANKNIFTY","NIFTYFINSRV2550","HEXT","BSLSENETFG",
        "BAJAJHLDNG","BANKETF","FINIETF","BHARATFORG","INDUSINDBK","KIRLOSENG","AKASH","ANKITMETAL",
        "HDFCNIFBAN","IDEA","KSHITIJPOL","AMBER","LUMAXTECH","SENSEXBETA","CERA","NIFTYPVTBANK",
        "PFOCUS","BANKNIFTY","SHADOWFAX","ESENSEX","ASAHIINDIA","NV20BEES","AAATECH","ATHERENERG",
        "GOLDENTOBC","SUPRAJIT","NIFTYFMCG","HDFCNIFTY","NIFTYCONSUMPTION","BANKBEES","RELIABLE","EMAMIREAL",
        "NIFTY","NIFTYADD","GROWWNET","PGHL","BILVYAPAR","NIFTYSERVSECTOR","SBIETFCON","CHOLAHLDNG",
        "IMFA","SENSEXADD","ABSLBANETF","MOSERVICE","TOP20","PRECWIRE","ITCHOTELS","MFSL",
        "CORONA","AARTIIND","PVTBANIETF","TOP15IETF","NAVKARURB","AXISCETF","ANANDRATHI","PGEL",
        "LTF","ENIFTY","NIFTYTOP10EW","SHILPAMED","BANKIETF","BANKADD","GODREJAGRO","SNXT50BETA",
        "MOCAPITAL","ALPL30IETF","INTERNET","CONSUMIETF","AXSENSEX","TATACOMM","UNIONBANK","CYBERMEDIA",
        "AXISNIFTY","HCG","NIFTYETF","SHIVATEX","PVTBANKADD","GROWWNIFTY","GROWWCAPM","NIFTYBEES",
        "NIFTYIETF","BHARTIHEXA","SUNDRMBRAK","BANKBETA","BANKBETF","NIFTYCAPITALMKT","SETFNIF50","ALKALI",
        "NIFTY1","NIFTYBETA","TOP100CASE","AXISBNKETF","KARURVYSYA","MAHKTECH","NIFTY100ESGSECLDR","LICNETFN50",
        "QNIFTY","NIFTY100","NAM-INDIA","SUPERHOUSE","HDFCVALUE","FMCGIETF","NIFTY100LIQ15","CONSUMBEES",
        "GROWWMOM50","SENSEXIETF","CONS","VIJAYA","PSUBANKADD","LICNFNHGP","SILLYMONKS","IDFNIFTYET",
        "MOM30IETF","NIFTYALPHALOWVOL","CARTRADE","ESSENTIA","BHANDARI","NIFTY200MOMENTM30","UTIAMC","MSCIADD",
        "RPOWER","GROWWN200","NIFTY50VALUE20","GICRE","SAHYADRI","BANKNIFTY1","NIF100IETF","NIFTYINDTOURISM",
        "INDUSTOWER","BSLNIFTY","JMFINANCIL","SILGO","SBIETFPB","NIFTYBETF","STARCEMENT","DALBHARAT",
        "INOXINDIA","PODDARMENT","GRWRHITECH","ANTHEM","ZENSARTECH","LOWVOL","GMRP&UI","SBINEQWETF",
        "DANGEE","NIFTY50EQLWGT","NIFTY100LOWVOL30","AVALON","EQUAL50ADD","NETF","NIFTY200","RELIGARE",
        "VIKRAMSOLR","ESG","NV20IETF","PTCIL","NIFTYTATA25CAP","AKZOINDIA","IVZINNIFTY","JSLL",
        "BBNPNBETF","RETAIL","NIFTYCASE","NIFTY500MOMENTM50","NEULANDLAB","WILLAMAGOR","BAIDFIN","NIFTY100ESG",
        "GMDCLTD","NIF100BEES","SBIBPB","AONENIFTY","NIFTYGROWSECT15","NIFTYPSUBANK","MSCIINDIA","MOMENTUM30",
        "LOWVOL1","CONSUMER","HEADSUP","NIFTY200ALPHA30","TRITURBINE","PSUBNKBEES","TOP10ADD","LLOYDSME",
        "BIRLACORPN","SUDEEPPHRM","JSWCEMENT","ALPHAETF","ZEELEARN","SBIMIDMOM","ABGSEC","HDFCGROWTH",
        "MONIFTY100","AARON","MOTOUR","LOWVOLIETF","UNOMINDA","HEG","PSUBNKIETF","NIFTY500",
        "HDFCPSUBK","ZFCVINDIA","SFL","DBSTOCKBRO","PRAENG","MOMOMENTUM","AARTECH","NIFTYTOTALMKT",
        "PATANJALI","HSCL","EQUAL50","PPAP","DCMNVL","JAIBALAJI","HDFCLOWVOL","SYRMA",
        "NARMADA","BBETF0432","GARFIBRES","HDFCBSE500","KHANDSE","CAPTRUST","MOQUALITY","HATSUN",
        "GLOBE","TMB","INDIAGLYCO","TI","3IINFOLTD","NIFTYINDDIGITAL","SEDEMAC","MOMENTUM",
        "HDFCPVTBAN","PNBHOUSING","AEGISLOG","ARTNIRMAN","JSL","SAPPHIRE","GSEC10ABSL","HPAL",
        "NIFTYCOMMODITIES","PSUBANK","BANKINDIA","NEXT30ADD","NIFTYMIDLIQ15","SHARIABEES","MOIPO","NPBET",
        "GROWWEV","EBBETF0433","AONETOTAL","MONIFTY500","TARMAT","EVINDIA","ELM250","METAL",
        "NIFTYALPHA50","NIFTY500MULTICAP","IKS","INDIACEM","KHAITANLTD","TNIDETF","NIFTYLARGEMID250","BAYERCROP",
        "NIFTYMETAL","BANKPSU","BSE500IETF","MOLOWVOL","AONETMMQ50","ETHOSLTD","KSB","SETFNIFBK",
        "MOMENTUM50","AXISCADES","BORORENEW","AXISHCETF","SURANASOL","ABDL","MSUMI","POWERINDIA",
        "HDFCMOMENT","ICICIAMC","GODFRYPHLP","MOMGF","SELECTIPO","AZAD","DBREALTY","LOVABLE",
        "OBCL","ONESOURCE","ANURAS","ACEINTEG","GSEC10IETF","INFRAIETF","JAYSREETEA","RVHL",
        "TMPV","NIFTY100EQLWGT","MODIRUBBER","INFRA","CNXINFRA","TCI","RAJTV","NIFTYMULTIMFG",
        "BASF","BBOX","KANORICHEM","EVIETF","MULTICAP","NV20","JWL","CASTROLIND",
        "BLBLIMITED","RPPL","MINDACORP","EBBETF0431","PRSMJOHNSN","MITCON","NIFTY50VALUE30","BHARATBOND-APR33",
        "NUVAMA","HDFCLIQUID","LTM","AIAENG","BHARATBOND-APR31","LIQUIDADD","LIQUIDSHRI","LIQUID1",
        "LIQUIDPLUS","LIQUIDBETF","CASHIETF","AONELIQUID","LIQGRWBEES","SBILIQETF","ELIQUID","NESCO",
        "HNDFDS","SDL26BEES","AARVI","LIQUIDCASE","GROWWLIQID","BHARATBOND-APR30","ABSLLIQUID","LIQUID",
        "LIQUIDSBI","LIQUIDBEES","LIQUIDETF","NIFTY50DIVPOINT","MOGSEC","GILT10BETA","TCIFINANCE","METALIETF",
        "NECLIFE","LAKPRE","EXCEL","GATECH","BHANDA-RE2","BHARATBOND-APR32","WABAG","LIQUIDIETF",
        "ENGINERSIN","TATAINVEST","NIFTYMIDSELECT","ORIENTLTD","KARMAENG","SHARDACROP","MHRIL","NIFTYM150MOMNTM50",
        "AXISTECETF","HDBFS","INCREDIBLE","MON50EQUAL","NIFTYGS48YR","HDFCQUAL","LICNETFGSC","NIFTYDIVOPPS50",
        "NIFTYGS10YR","MONEXT50","DGCONTENT","AXISBPSETF","NIFTYGS1115YR","NIFTYGS813YR","CNXIT","NIFTYGSCOMPSITE",
        "LICNETFSEN","KIRLOSBROS","ATAM","BALAJEE","GROWWSC250","CNXMNC","EBBETF0430","NIFTYGS10YRCLN",
        "ORKLAINDIA","COMMOIETF","GILT5BETA","LTGILTBEES","NATCAPSUQ","SIL","NIFTY200QUALITY30","NIFTYINDIAMFG",
        "NIFTYMIDCAP50","NIFTYMULTIINFRA","LTGILTCASE","ELGIEQUIP","SKYGOLD","ITBETA","DJML","SNXT30BEES",
        "TVVISION","ITIETF","NIFTYMS400MQ100","WORTHPERI","GILT5YBEES","MURUDCERA","MOTOGENFIN","NIFTYCONSURDURBL",
        "MOMIDMTM","LENSKART","MOM100","NIFTY100EW","ECAPINSURE","SETF10GILT","IITL","AGRITECH",
        "TTL","SBIETFIT","RELCHEMQ","DYNPRO","HECPROJECT","MOINFRA","IT","DTIL",
        "CNXMIDCAP","DCBBANK","MOSMALL250","NIFTYGS15YRPLUS","BCONCEPTS","MASPTOP50","GROWWMETAL","NIFTYSML250MQ100",
        "GROWWMC150","NEXT50ADD","MIDSMALL","HDFCNIFIT","MFML","ASTRAZEN","MAKEINDIA","MNC",
        "SWANDEF","QUALITY30","ADROITINFO","ENRIN","NEXT50","HBLENGINE","AWL","CNXNIFTYJUNIOR",
        "NIFTYQLITY","BGLOBAL","NIFTYMIDSMALLCAP400","NIFTYSMALLCAP250","INFRABEES","GSEC5IETF","ITETF","QUAL30IETF",
        "NIFTYMIDCAP150","POLYMED","SHANKARA","ATLANTAELE","JIOFIN","NIFTYSMALLCAP50","APLLTD","VENTIVE",
        "MID150CASE","VARROC","KAKATCEM","EQUAL200","MID150BEES","HDFCSML250","LTFOODS","PWL",
        "NKIND","SMALLCAP","FLEXITUFF","360ONE","DIVOPPBEES","ALPHA","ITBEES","GANESHHOU",
        "MIDCAPBETA","DCM","BECTORFOOD","UJJIVANSFB","SGL","TECH","GROWWPOWER","TRANSRAILL",
        "MIDSELIETF","PARASPETRO","JUBLPHARMA","DELHIVERY","GSPL","NEXT50IETF","UFO","ATLANTAA",
        "SBIETFQLTY","TIMETECHNO","DEFENCE","UYFINCORP","CNXSMALLCAP","EQUITASBNK","DHRUV","ATALREAL",
        "WELCORP","EUREKAFORB","WEIZMANIND","SML100CASE","NIFTYCHEMICALS","BLACKBUCK","BLUEJET","ICRA",
        "NIFTYMEDIA","PONNIERODE","VALIANTLAB","FIBERWEB","MIDCAPETF","ARVINDFASN","EDELWEISS","HDFCNEXT50",
        "PALREDTEC","ARE&M","SMALL250","NIFTYMICROCAP250","WAAREERTL","LFIC","ICICIB22","CUBEXTUB",
        "MIDCAPIETF","SALONA","AXISVALUE","UCOBANK","PGIL","IGL","HNGSNGBEES","REDINGTON",
        "GSEC10YEAR","KRN","GALLANTT","SPLPETRO","LPDC","PARAS","FELDVR","SETFNN50",
        "MOMNC","SVPGLOB","PRIVISCL","21STCENMGM","NOVAAGRI","NIFTYINDDEFENCE","PPLPHARMA","AMAGI",
        "MIDQ50ADD","CLEDUCATE","JAYNECOIND","SHIVAMILLS","MIDCAP","TECHNOE","MON100","JAINREC",
        "NIFTYM150QLTY50","TVSHLTD","JUNIORBEES","NATHBIOGEN","EMULTIMQ","VAL30IETF","PKTEA","IGIL",
        "DIAMINESQ","MAFANG","GLAXO","PAVNAIND","MODEFENCE","COHANCE","NIVABUPA","INGERRAND",
        "RKFORGE","OMAXAUTO","GROWWCHEM","ONELIFECAP","UMESLTD","SMLT","VASWANI","ABSLMSCIN",
        "NEXT50BETA","AARNAV","GPIL","MONQ50","SURYALAXMI","MOHEALTH","NLCINDIA","ROML",
        "HFCL","AGARWALEYE","IIFLCAPS","PCBL","EDUCOMP","GROWWLOVOL","NATCOPHARM","GROWWDEFNC",
        "VTL","EIHOTEL","BAJAJHFL","BIOFILCHEM","INFOMEDIA","MOVALUE","CTE","NIFTY50PR1XINV",
        "TNTELE","MEP","REDTAPE","PHARMABEES","INDOWIND","PREMIER","CNXENERGY","ABBOTINDIA",
        "MAHLIFE","NIFTY50TR1XINV","LOTUSDEV","MOENERGY","CHOICEIN","DIACABS","HEALTHCARE","SHYAMMETL",
        "SONATSOFTW","IVP","LICNMID100","SMARTLINK","TREEHOUSE","WINSOME","PRUDENT","NITIRAJ",
        "RVTH","HONASA","AUSOMENT","BLS","ENERGY","GROWWNXT50","HDFCMID150","JSWINFRA",
        "HBSL","DIVIDEND","FLEXIADD","MAHABANK","BELRISE","NEXTMEDIA","IEX","SHAILY",
        "GILLANDERS","WOCKPHARMA","SIGIND","IOB","PATINTLOG","FMNL","PILITA","TSFINV",
        "ITADD","CNXPHARMA","KPIL","NAGREEKCAP","FINCABLES","GRAPHITE","CENTRALBK","NIFTYCPSE",
        "ELECON","LLOYDSENGG","MOHITIND","SADBHIN","TATACAP","VIYASH","ZENITHSTL","GAYAHWS",
        "ASHOKAMET","JUBLINGREA","MARKSANS","CEMPRO","KIOCL","LATTEYS","NIFTYHEALTHCARE","LASA",
        "YATHARTH","URAVIDEF","GABRIEL","HEALTHIETF","MMTC","AKUMS","CHEMICAL","HEALTHY",
        "NIFTYMIDSMLHLTH","GRAVITA","INDBANK","JYOTICNC","PRAXIS","SAMMAANCAP","AEQUS","SURANAT&P",
        "RHIM","NUVOCO","CPSEETF","KANANIIND","CNXPSE","AVL","ARENTERP","JBCHEPHARM",
        "ALKYLAMINE","HEALTHADD","INTENTECH","MOREALTY","NIBL","PNC","SHANTI","FLFL",
        "SHAKTIPUMP","VOLTAMP","SCHNEIDER","CNXREALTY","MOPSE","NIFTYOILANDGAS","CAPLIPOINT","UBL",
        "LGEINDIA","CGPOWER","ALMONDZ","BLUESTARCO","TEAMGTY","GROWWRAIL","PIONEEREMB","THANGAMAYL",
        "AKSHARCHEM","GROWWHOSPI","TARAPUR","V2RETAIL","CROWN","OSWALSEEDS","TRAVELFOOD","JBMA",
        "ISGEC","REGENCERAM","CEATLTD","SUNDRMFAST","CINELINE","PARADEEP","ABLBL","OFSS",
        "NH","BLUESTONE","ABSLPSE","PLAZACABLE","ORIENTALTL","IL&FSTRANS","NIACL","TITAGARH",
        "ANANTRAJ","MAXESTATES","GEEKAYWIRE","SANOFI","DNAMEDIA","GROBTEA","STLTECH","AFFORDABLE",
        "SUVIDHAA","IVC","SIGNATURE","DBL","PRAKASHSTL","NSLNISP","JETFREIGHT","MAHSCOOTER",
        "BLUECHIP","TPHQ","CPPLUS","BEML","SYMPHONY","ANSALAPI","GOLD360","BROOKS",
        "UTLSOLAR","GROWWPSE","INOXGREEN","MCL","ABMINTLLTD","DIGIDRIVE","ORCHASP","AEGISVOPAK",
        "MEESHO","NORBTEAEXP","NEXT50ETF","OILIETF","MOKSH","CONCORDBIO","METROBRAND","PAR",
        "ALIVUS","EPL","BBTC","TRIGYN","FIEMIND","MOGOLD","AIRAN","CCHHL",
        "STEELCITY","BEARDSELL","KEYFINSERV","TECILCHEM","LYPSAGEMS","PSB","VAISHALI","BDL",
        "GOLDETF","MANUFGBEES","NEPHROPLUS","INDOUS","PALASHSECU","TRF","AGROPHOS","VETO",
        "HYBRIDFIN","BRNL","SMALLADD","BSL","MIDHANI","AMJLAND","SCI","AERONEU",
        "ODIGMA","KIRLPNU","KALYANIFRG","AIIL","STARPAPER","FINPIPE","GROWWRLTY","GVT&D",
        "WELENT","MID150","PEARLPOLY","LAXMICOT","OMKARCHEM","CPCAP","SHIVAMAUTO","RADIOCITY",
        "KAJARIACER","WEWORK","GATECHDVR","CEREBRAINT","ABSLNN50ET","TATAGOLD","GOLDBEES","KWIL",
        "TIPSFILMS","MASFIN","NIPPOBATRY","KCPSUGIND","ENERGYDEV","ANMOL","MGL","AJOONI",
        "IMPEXFERRO","GUJGASLTD","GUJRAFFIA","DAMODARIND","PRAJIND","LICMFGOLD","BSLGOLDETF","QGOLDHALF",
        "FEL","SHRENIK","ALPA","NAVA","KOTARISUG","AROGRANITE","JKLAKSHMI","ARCHIDPLY",
        "GROWWGOLD","ASPINWALL","HCG-RE","CHOICEGOLD","CORALFINAC","IVZINGOLD","ASTRAMICRO","GOLDADD",
        "ANTGRAPHIC","TEGA","PNGJL","SETFGOLD","HDFCGOLD","GOLD1","VARDHACRLC","USHAMART",
        "KALPATARU","RUDRA","ALANKIT","BALUFORGE","GOLDBETA","SHAHALLOYS","GAEL","GOLDIETF",
        "TRANSWORLD","LAL","KANSAINER","IFCI","AONEGOLD","PRITIKAUTO","SWANCORP","BBNPPGOLD",
        "UCAL","KEC","KTKBANK","SHEMAROO","GALAXYSURF","ASTERDM","GOLDCASE","KEEPLEARN",
        "HYUNDAI","BHARATGEAR","CORDSCABLE","LGBBROSLTD","UNIVASTU","RUBICON","INDIANCARD","ACE",
        "TIJARIA","SSDL","GOLDBND","GENUSPOWER","MEDPLUS","NIRAJ","AKG","UNIONGOLD",
        "AIROLAM","RAJMET","ACI","RELAXO","EGOLD","AXISGOLD","GTL","JPPOWER",
        "SGMART","APOLLO","RITES","CALSOFT","RAILTEL","RANASUG","LCCINFOTEC","INVENTURE",
        "BANG","SITINET","FCONSUMER","NAGREEKEXP","GOYALALUM","JKPAPER","GLOBALVECT","SAGARDEEP",
        "TEXMOPIPES","CENTEXT","ROSSELLIND","SOUTHBANK","SHYAMCENT","ECLERX","WIPL","TWCGOLDETF",
        "BATAINDIA","TFL","NDGL","NILAINFRA","SAFARI","AUTOIND","SONAMLTD","SAKUMA",
        "TOKYOPLAST","INDTERRAIN","HINDCON","APOLSINHOT","GANGESSECU","ASTRON","MALUPAPER","STAR",
        "ALOKINDS","SAMBHAAV","M&MFIN","VMSTMT","SHREEJISPG","FDC","OMFREIGHT","LAGNAM",
        "BALPHARMA","GSS","AARTIPHARM","RKDL","FSL","SIKKO","SELMC","IRCON",
        "FCSSOFT","GTECJAINX","ABREL","RUCHINFRA","MARALOVER","ACCURACY","SINTERCOM","DIGJAMLMTD",
        "ELGIRUBCO","GANGAFORGE","HILTON","RSSOFTWARE","TOTAL","KAMOPAINTS","KAUSHALYA","AAREYDRUGS",
        "SOBHA","LLOYDSENT","WAKEFIT","SHEKHAWATI","PARSVNATH","BVCL","BANKA","AMDIND",
        "SOMICONVEY","MADHAV","KMSUGAR","THELEELA","JHS","CRISIL","MANGALAM","SUDARSCHEM",
        "PARKHOSPS","VIKASLIFE","MAGNUM","TARIL","DEEPAKNTR","SRPL","FRACTAL","SILVERBND",
        "GSLSU","HINDPETRO","BPL","DRCSYSTEMS","ZODIACLOTH","NAGAFERT","LOYALTEX","EMMBI",
        "CELEBRITY","GOACARBON","KHADIM","ORTINGLOBE","MASKINVEST","SPENCERS","SAMPANN","ACMESOLAR",
        "AMBICAAGAR","MOSILVER","CLEANMAX","OSIAHYPER","TATSILV","BLUECOAST","BASML","COMPINFO",
        "SILVERBETA","ATLASCYCLE","SILVER1","AHLADA","VITAL","SILVERCASE","NURECA","ALPHAGEO",
        "A2ZINFRA","DPWIRES","ESILVER","NECCLTD","SILVERIETF","SILVER","USK","SILVER360",
        "BHARATCOAL","DELPHIFX","GROWWSLVR","SILVERBEES","SETCO","PIGL","TOUCHWOOD","KESORAMIND",
        "SILVERADD","DUCON","HDFCSILVER","HISARMETAL","EMBDL","VCL","TAINWALCHM","3PLAND",
        "SBISILVER","JMA","INDIAVIX","MOIL","AXISILVER","KOHINOOR","AONESILVER","SARDAEN",
        "DELTAMAGNT","ZENITHEXPO","MTEDUCARE","MADHUCON","MANAKALUCO","AGSTRA","SILVERAG","SADBHAV",
        "ARSHIYA","HPIL","DIL","EUROTEXIND","TGBHOTELS","TIGERLOGS","ROLLT","SKIL",
        "SIMBHALS","HDIL","MORARJEE","VIVIDHA","RCOM","SANCO","GENSOL","MANUGRAPH",
        "AAKASH","NOIDATOLL","SHREYANIND","LEXUS","LANCORHOL","EASTSILK","ABAN","BOHRAIND",
        "SABEVENTS","CMICABLES","SANDUMA","UMIYA-MRO","UNIINFO","AHLUCONT","HDFCNIF100","VINNY",
        "RACE","RAJSREESUG","VIPCLOTHNG","BALAXI","KPIGREEN","KREBSBIO","MITTAL","MUKTAARTS",
        "VLEGOV","VIKASECO","VSTL","CHEMBOND","AKSHOPTFBR","ASMS","FILATFASH","SAKHTISUG",
        "RADAAN","KRBL","VISHWARAJ","PRITI","PRUDMOULI","GLOBECIVIL","REPL","BTML",
        "GESHIP","LAMBODHARA","BYKE","DSFCL","GULFPETRO","JOCIL","ADL","BAGFILMS",
        "JISLDVREQS","DHARAN","ISFT","SPLIL","RKEC","ICDSLTD","UMAEXPORTS","ATGL",
        "VIRINCHI","KRIDHANINF","MODTHREAD","COMPUSOFT","SUPERSPIN","HGM","MIDCAPADD","SHYAMTEL",
        "COUNCODOS","HAVISHA","OILCOUNTUB",
    ]
    seen = set()
    result = []
    for sym in symbols:
        if sym not in seen:
            seen.add(sym)
            result.append({"symbol": sym, "name": sym, "sector": "Unknown"})
    return result


def main():
    parser = argparse.ArgumentParser(description="Build NSE symbol list for TradEdge Scanner")
    parser.add_argument("--from-csv", type=str, help="Path to CSV export")
    parser.add_argument("--builtin-only", action="store_true", help="Use built-in list only")
    args = parser.parse_args()

    symbols = []

    if args.from_csv:
        print(f"📄 Building from CSV: {args.from_csv}")
        symbols = build_from_csv(args.from_csv)
    elif args.builtin_only:
        print("📦 Using built-in list (2803 symbols, all market caps)")
        symbols = get_builtin_symbols()
    else:
        print("🌐 Fetching ALL NSE stocks from official sources...")
        symbols = fetch_nse_equity_list()
        if not symbols:
            print("  ⚠ Network failed. Using built-in list.")
            symbols = get_builtin_symbols()
        else:
            builtin = get_builtin_symbols()
            existing = {s["symbol"] for s in symbols}
            added = 0
            for s in builtin:
                if s["symbol"] not in existing:
                    symbols.append(s)
                    existing.add(s["symbol"])
                    added += 1
            if added:
                print(f"  ➕ Merged {added} extra symbols from built-in list")

    # Filter & deduplicate
    seen = set()
    unique = []
    for s in symbols:
        sym = s["symbol"]
        if not sym or len(sym) > 20 or sym in seen:
            continue
        seen.add(sym)
        unique.append(s)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(unique, f, indent=2)

    print(f"\n{"=" * 50}")
    print(f"  ✅ Saved {len(unique)} symbols to {OUTPUT_FILE}")
    print(f"  Coverage: Mega → Large → Mid → Small → Micro cap")
    print(f"{"=" * 50}")


if __name__ == "__main__":
    main()
